"use client";

import { useMemo, useState } from "react";
import { FileUp, ArrowRight, RefreshCcw, Plus, AlertTriangle } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { apps, type CatalogItem } from "@/data/apps";
import { parseAuditCsv, type AuditRow, type CsvRowError } from "@/lib/parsing/csv";
import { cn } from "@/lib/utils";

interface MatchResult {
  row: AuditRow;
  match?: CatalogItem;
  matchType: "exact-name" | "fuzzy-name" | "path" | "repo" | "none";
  conflicts: string[];
}

export function CSVImportPreview() {
  const [data, setData] = useState<AuditRow[]>([]);
  const [errors, setErrors] = useState<CsvRowError[]>([]);
  const [fileName, setFileName] = useState<string | null>(null);

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setData([]);
    setErrors([]);

    const reader = new FileReader();
    reader.onload = (loadEvent) => {
      const fileText = loadEvent.target?.result;
      if (typeof fileText !== "string") {
        setErrors([{ line: 1, message: `Could not read ${file.name} as text.` }]);
        return;
      }

      const result = parseAuditCsv(fileText);
      setData(result.rows);
      setErrors(result.errors);
    };
    reader.onerror = () => {
      setData([]);
      setErrors([{ line: 1, message: `Could not read ${file.name}.` }]);
    };
    reader.readAsText(file);
  };

  const matches = useMemo(() => {
    return data.map((row) => {
      let match: CatalogItem | undefined;
      let matchType: MatchResult["matchType"] = "none";
      const conflicts: string[] = [];

      match = apps.find((catalogItem) => catalogItem.name.toLowerCase() === row.name.toLowerCase());
      if (match) {
        matchType = "exact-name";
      } else {
        match = apps.find((catalogItem) => catalogItem.localPath === row.localPath);
        if (match) {
          matchType = "path";
        } else {
          match = apps.find((catalogItem) => catalogItem.repoUrl === row.repoUrl);
          if (match) matchType = "repo";
        }
      }

      if (match) {
        if (row.repoUrl && match.repoUrl && row.repoUrl !== match.repoUrl) {
          conflicts.push("repoUrl");
        }
        if (row.localPath && match.localPath && row.localPath !== match.localPath) {
          conflicts.push("localPath");
        }
      }

      return { row, match, matchType, conflicts };
    });
  }, [data]);

  const stats = useMemo(() => {
    return {
      total: matches.length,
      new: matches.filter((matchResult) => matchResult.matchType === "none").length,
      matched: matches.filter((matchResult) => matchResult.matchType !== "none").length,
      conflicts: matches.filter((matchResult) => matchResult.conflicts.length > 0).length,
    };
  }, [matches]);

  if (data.length === 0) {
    return (
      <Card className="border-dashed border-2">
        <CardContent className="flex flex-col items-center justify-center py-12 space-y-4">
          <div className="p-4 bg-muted rounded-full">
            <FileUp className="h-8 w-8 text-muted-foreground" />
          </div>
          <div className="text-center">
            <h3 className="text-lg font-medium">Upload Project Audit CSV</h3>
            <p className="text-sm text-muted-foreground">
              Select the CSV file generated by the Copilot audit
            </p>
          </div>
          {errors.length > 0 && (
            <div className="w-full max-w-md p-4 rounded-md border border-rose-300 bg-rose-50 dark:bg-rose-950/30 text-rose-800 dark:text-rose-300 text-sm space-y-2">
              <div className="flex items-center gap-2 font-semibold">
                <AlertTriangle className="h-4 w-4 text-rose-600" />
                CSV Import Failed
              </div>
              <ul className="list-disc pl-5 space-y-1 text-xs">
                {errors.map((error) => (
                  <li key={`${error.line}-${error.message}`}>{error.message}</li>
                ))}
              </ul>
            </div>
          )}
          <Input
            type="file"
            accept=".csv"
            className="hidden"
            id="csv-upload"
            onChange={handleFileUpload}
          />
          <Button asChild>
            <label htmlFor="csv-upload" className="cursor-pointer">
              Select File
            </label>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            Import Preview: {fileName}
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setData([]);
                setErrors([]);
                setFileName(null);
              }}
            >
              <RefreshCcw className="h-4 w-4" />
            </Button>
          </h2>
          <p className="text-muted-foreground">
            Comparing audit data with existing JoshHub inventory
          </p>
        </div>
      </div>

      {errors.length > 0 && (
        <div className="p-4 rounded-md border border-amber-300 bg-amber-50 dark:bg-amber-950/30 text-amber-900 dark:text-amber-300 text-sm space-y-2">
          <div className="flex items-center gap-2 font-semibold">
            <AlertTriangle className="h-4 w-4 text-amber-600" />
            {errors.length} row{errors.length === 1 ? "" : "s"} had validation errors and{" "}
            {errors.length === 1 ? "was" : "were"} skipped:
          </div>
          <ul className="list-disc pl-5 space-y-1 text-xs max-h-32 overflow-y-auto">
            {errors.map((error) => (
              <li key={`${error.line}-${error.message}`}>{error.message}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
              Total Rows
            </CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold">{stats.total}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-emerald-600 uppercase tracking-wider">
              Matches
            </CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-emerald-700">{stats.matched}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-blue-600 uppercase tracking-wider">
              New Projects
            </CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-blue-700">{stats.new}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-rose-600 uppercase tracking-wider">
              Conflicts
            </CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-rose-700">{stats.conflicts}</div>
          </CardContent>
        </Card>
      </div>

      <div className="border rounded-lg overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-muted/50 border-b">
            <tr>
              <th className="px-4 py-3 text-left font-medium">Audit Entry</th>
              <th className="px-4 py-3 text-center w-16">Match</th>
              <th className="px-4 py-3 text-left font-medium">JoshHub Project</th>
              <th className="px-4 py-3 text-left font-medium">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {matches.map((matchResult, rowIndex) => (
              <tr
                key={`${matchResult.row.name}-${rowIndex}`}
                className={cn(
                  matchResult.conflicts.length > 0 && "bg-rose-50/50 dark:bg-rose-950/10"
                )}
              >
                <td className="px-4 py-4">
                  <div className="font-semibold">{matchResult.row.name}</div>
                  <div className="text-xs text-muted-foreground font-mono mt-1">
                    {matchResult.row.localPath || "No path"}
                  </div>
                </td>
                <td className="px-4 py-4 text-center">
                  {matchResult.match ? (
                    <div className="flex flex-col items-center gap-1">
                      <ArrowRight className="h-4 w-4 text-emerald-500" />
                      <Badge variant="outline" className="text-[10px] py-0">
                        {matchResult.matchType}
                      </Badge>
                    </div>
                  ) : (
                    <Plus className="h-4 w-4 text-blue-500 mx-auto" />
                  )}
                </td>
                <td className="px-4 py-4">
                  {matchResult.match ? (
                    <div>
                      <div className="font-semibold flex items-center gap-2">
                        {matchResult.match.name}
                        {matchResult.conflicts.length > 0 && (
                          <AlertTriangle className="h-3 w-3 text-rose-500" />
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground font-mono mt-1">
                        {matchResult.match.localPath || "No path"}
                      </div>
                      {matchResult.conflicts.map((conflictField) => (
                        <div
                          key={conflictField}
                          className="text-[10px] text-rose-600 mt-1 font-medium"
                        >
                          Conflict: {conflictField}
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-muted-foreground italic text-xs">New entry candidate</div>
                  )}
                </td>
                <td className="px-4 py-4">
                  {matchResult.match ? (
                    <Badge
                      variant="outline"
                      className="bg-emerald-50 text-emerald-700 border-emerald-200"
                    >
                      Update metadata
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                      Create project
                    </Badge>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
